---

# Implement manual preparation steps for SLES-12
# The tasks' name follows:
#   - SUSE Linux Enterprise Server 12.x for SAP Applications &on ¶JuUDtLon Guide for SAP HANA x86_64 and POWER Architectures
#   - SAP Notes for RHEL OS recommendations


#- name: SAP Note 2593824 - Linux Running SAP applications compiled with GCC 7.x
#  package:
#    name: "{{ item }}"
#    state: present
#  with_items:
#    - libgcc_s1
#    - libstdc++6
#    - libatomic1
#
- name: SAP Note 2593824 - Linux Running SAP applications compiled with GCC 7.x
  command:  zypper -n install libgcc_s1 libstdc++6 libatomic1
